### ISSUE TITLE
insmod error

### ISSUE THREAD

**Issue by hheekwak** [hhsw0322/CS596-RT2024Fall-Group01#3]
Hello Group 01, 

I hope this message finds you well. 
The kernel compile and installation worked well, which is great!

However, the loadable kernel module doesn't load properly. Because the majority of grade points are from your reservation management, I may need to hold the grading until you fix it. 

Since we are at the end of the semester, I'm not sure how long I can hold the grading. I would appreciate it if you let me know whether you want to try further or not. 

Thank you, 

Hyunhee

![insmod_error](https://github.com/user-attachments/assets/5bd28eef-4793-4bf9-b5ab-5e8ff31a29cd)

![rsv](https://github.com/user-attachments/assets/bcff1894-e463-4cb2-90cc-20e4c1c87653)

![dmesg](https://github.com/user-attachments/assets/fb0e8563-005f-4fa0-aa72-bb5008ffa637)

**Comment by hhsw0322** [comment]
Hello,

I had questions about the loadable kernel since the issue is in the
Makefile. It works on my end but I think it might be because of a different
file structure on your end which was what happened in Project 2 too I
believe. I initially hard coded the kernel source but because the file path
is different on your end it doesn’t load. I tried to soft code it using
../.. as well so I’m lost on that part, to be completely honest.

Is there anyway you could help us with the lkm Makefile?

Best,
Su

**Comment by hhsw0322** [comment]
Hi,

We’ll keep trying to debug the lkm today as last.
Thank you so much for your patience.

Best,
Su

**Comment by hheekwak** [comment]
Hi, 
Yes. The original Makefile (and proj2) had an absolute path, so I changed it and was be able to grad for proj2.
The kernel module itself compiled well with your updated Makefile. Thus it doesn't seem Makefile issue.

What I found is the message is about some kind of compatible issue. I am also trying to figure out but it hasn't work out well yet. Hope you find a way!

Thanks, 

Hyunhee

**Comment by hhsw0322** [comment]
Hi,

I think it was a problem in my syscalls.c file where I didn’t Export the
sys_set_rsv and sys_cancel_rsv so we’re debugging that, compiling the
source kernel again (which compiled successfully just now!) and now we’re
trying to test it on the raspberry pi. Hopefully that works out well.

Please let us know if you find anything else either.

Best,
Su

**Comment by hhsw0322** [comment]
Hi!

We edited our rsv_module.c to debug it because when it did load on
raspberry pi it was asking for a pid so we edited rsv_module.c to make sure
it was working with the default pid=0 but even after changing that,
compiling, copying to the sdcard and running it on raspberry pi, it's still
giving us this error. We also verified that the kernel running is the
latest compile (see screenshot with uname -a ran).

Please take a look at the edited syscalls.c file (with the export lines
added at the end) and the edited rsv_module.c file to let us know if
there's the same errors on your end. test_rsv also did not give us any
output despite it giving outputs on your end so we're confused on how to
proceed.

Please feel free to grade us as we are completely lost and let us know how
we should proceed.
We'll be researching and trying to get a proper start on project 4 in the
meantime over the weekend. Thank you for your help.

Best,
Group 01, Su[image: Screenshot 2024-12-13 at 2.28.34 PM.png]

**Comment by hhsw0322** [comment]
Hi,

We would appreciate a template or a lkm c file we could use to proceed with
project 4, even if we’re graded on what we have right now for project 3 so
we can proceed with project 4 because I’m concerned how this is going make
project 4 non functional although we’ve been researching on it and getting
started on the hardware part of it.

Please give us guidance on this.
Thank you!

Best,
Su

**Comment by noaa99** [comment]
For project3, I don't think you need a module. I see that the system calls were implemented in the /kernel directory.

For project4, basically project3 will be a foundational framework. If that works, it'll not be a challenge utilizing a sensor with running real-time tasks. Good luck!

Best,
Hyunjong

**Comment by hhsw0322** [comment]
Hi Professor,

Does that mean we would be able to proceed without the modules file since
we already implemented the syscalls in the kernel directory?

I’ll make the changes! Thank you for your prompt response.

Best,
Su

**Comment by noaa99** [comment]
Yeah, I don't know the purpose of your loadable kernel module. I went through your module source code and they're not used when you call system calls from your application.

**Comment by hhsw0322** [comment]
Ok, thanks for the clarification! This really helps!
